### ISSUE TITLE
improve import code to be contributed by others

### ISSUE THREAD

**Issue by larrycai** [tobegit3hub/pirate#7]
In the Go code for `import`, there is hard coded to this github repo.

    _ "github.com/tobegit3hub/pirate/routers"

It will be difficult to be contributed by others since they need fork and point to their own repo.

Can we change it to relative path ?

**Comment by tobegit3hub** [comment]
Relative path is not recommended in go projects. Maybe all beego projects have the same problem. @astaxie How can you fix that?

**Comment by astaxie** [comment]
Actually it's the Go's problem. it's really hard to fix it. So go team develop a new tools `gorename`: https://godoc.org/golang.org/x/tools/refactor/rename

**Comment by tobegit3hub** [comment]
For more usage of `gorename, please refer to https://texlution.com/post/gorename/ `. I think it's just a refactoring tool and doesn't fix this "problem".

After further consideration, I don't think it's a "problem" for us. Because we always know about what libraries we're gonna use. After forking the project, we may want to add more routers and we should change to import the personal routers library. The one from upstream will not change after merging this.

**Comment by tobegit3hub** [comment]
I will close it with won't fix. Feel free to re-open it if we have any problem about this :smile:
